config/routes.rb
Rails.application.routes.draw do
  devise_for :ongs
  devise_for :admins

  resources :ongs
  get "forum_topics/:id/new_report_topic" => 'forum_topics#new_report_topic', as: :new_report_topic
  patch "forum_topics/:id/create_report_topic" => 'forum_topics#create_report_topic', as: :create_report_topic
  get "forum_topics/:id/new_report_post" => 'forum_topics#new_report_post', as: :new_report_post
  patch "forum_topics/:id/create_report_post" => 'forum_topics#create_report_post', as: :create_report_post
  get "admins/reports_index" => 'admins#reports_index'
  resources :forum_themes do
    resources :forum_topics
  end

  resources :forum_topics do
      resources :forum_posts
  end
  resources :forum_posts

  get "portal/list" => "portal_posts#list"
  get "portal/new" => "portal_posts#new"
  post "portal/new" => "portal_posts#create"

  resources :forum_themes
  resources :forum_topics
  resources :forum_posts
  

  resources :parsers do
    collection { post :importCare }
    collection { post :importRate }
  end

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'about'=> 'static_pages#about'
  get 'opendata' => 'static_pages#opendata'
  resources :mortality_rates
  resources :units
  resources :care_units
  resources :events
  resources :portal_posts
end

app/models/forum_theme.rb
class ForumTheme< ActiveRecord::Base
	# Use forum_theme as a rolify resource
  resourcify

	has_many :forum_topics, dependent: :destroy

    # Paperclip gem sintax for upload image files.
	has_attached_file :image_file, :styles => {}, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/

	TITLE_MIN_LENGTH = 2
	DESCRIPTION_MIN_LENGTH = 2
	validates :title, presence: true, :length => {:minimum => TITLE_MIN_LENGTH}, uniqueness: true
	validates :description, presence: true, :length => {:minimum => DESCRIPTION_MIN_LENGTH}
end

app/controllers/forum_themes_controller.rb
class ForumThemesController < ApplicationController
  # Use this controller as a resource of CanCan and Rolify
  load_and_authorize_resource

  include ApplicationHelper
	PAGINATION_RANGE = 5

  def index
    # Get last forum topics
    ungrouped_last_forum_topics = get_last_forum_topics(9)
    # Group the last forum topics in specified sub-lists.
    # To see the method structure, go to the application helper.
    @grouped_last_forum_topics = create_list_groups(ungrouped_last_forum_topics, 3)
    @forum_themes = ForumTheme.all
  end

  def show

    set_forum_theme
    # If the user is searching for something, returns the result of the research
    if params[:search]
      @forum_topics = @forum_theme.forum_topics.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: PAGINATION_RANGE)
    else
      @forum_topics = @forum_theme.forum_topics.all.order('created_at DESC').paginate(page: params[:page], per_page: PAGINATION_RANGE)
    end
    number_of_pages = (@forum_topics.count.to_f / PAGINATION_RANGE.to_f).ceil
    @pages = 1..number_of_pages
    @page = params[:page]
    @page ||= 1
    logger.debug "Quantity of paginated topics: #{ @forum_topics.count }."
    logger.debug "Number of pages: #{ number_of_pages }."
    logger.debug "Current page: #{ @page }."
  end

  def new
    @forum_theme = ForumTheme.new
  end

  def create
    @forum_theme = ForumTheme.new(forum_theme_params)

    if @forum_theme.save
        redirect_to '/forum_themes'
    else
        render 'new'
    end
  end

  def edit
    set_forum_theme
  end

  def update
    set_forum_theme
    if @forum_theme.update(forum_theme_params)
      flash[:success] = "Tema atualizado!"

      redirect_to @forum_theme
    else
      render :edit
    end
  end

  def destroy
    set_forum_theme
    @forum_theme.destroy
    redirect_to forum_themes_path
  end

  private
    # Method to get some forum topics
    def get_last_forum_topics(quantity)
      return ForumTopic.order(created_at: :desc).limit(quantity)
    end

    # Method to take a ForumTheme with a specified identifier
    def set_forum_theme
      @forum_theme = ForumTheme.find(params[:id])
    end

    def forum_theme_params
        params.require(:forum_theme).permit(:title, :description, :image_file)
    end
end

app/views/forum_themes/_form_new_edit.html.erb
<!--This file contains the templeate of fields for creating and editing a new theme-->

<h1><%= action_name %></h1>

<%= form_for(@forum_theme) do |field| %>
  <p>Tema: </p>
  <%= field.text_field :title%>

  <p>Descrição: </p>
  <%= field.text_field :description%>
    
  <%= field.submit "criar tema"%>
<% end %>
    

app/views/forum_themes/edit.html.erb
<h3><%=@forum_theme.title%></h3>

<%= render 'form_new_edit' %>

app/views/forum_themes/index.html.erb
<section id="title" class="emerald">
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Fórum</h1>
            <p>Escolha um tema e lembre-se que esse fórum é totalmente anônimo.</p>
        </div>
    </div>
</div>
</section>
<section id="portfolio" class="container">
	<ul class="portfolio-filter">
      <li><a class="btn btn-default" href="#" data-filter="*">Todos</a></li>
      <% @forum_themes.each do |each_forum_theme| %>
        <li><a class="btn btn-default" href="#" data-filter=".<%= each_forum_theme.title.split(" ")[0] %>"><%= each_forum_theme.title.split(" ")[0] %></a></li>
      <% end %>

	</ul><!--/#portfolio-filter-->
    <br>
	<ul class="portfolio-items col-3">
    <% @forum_themes.each do |each_forum_theme| %>
	    <li class="portfolio-item <%= each_forum_theme.title.split(" ")[0] %>">
		<div class="item-inner">
			<%if each_forum_theme.image_file.present? %>
				<%= image_tag(each_forum_theme.image_file.url()) %>
			<%else%>
				<%= image_tag("nikn_default_banner.png")  %>
			<%end%>
		    <h5><%= each_forum_theme.title %></h5>
		    <div class="overlay">
              <%= link_to forum_theme_path(each_forum_theme), class: "preview btn btn-danger" do %>
		        <i class="icon-eye-open"></i>
              <% end %>
          </div>
		</div>
      <% end %>
	</ul>
</section><!--/#portfolio-->

app/views/forum_themes/new.html.erb
<h3> Criar novo Tema </h3>
<%= render 'form_new_edit'%>

app/views/forum_themes/show.html.erb
<section id="title" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1><%= @forum_theme.title %></h1>
                <p><%= @forum_theme.description %></p>
            </div>
            <div class="col-sm-6">
                <ul class="breadcrumb pull-right">
                  <li><%= link_to "Início", root_path %></li>
                  <li class="active"><%= link_to "Temas", forum_themes_path %></li>
                </ul>
            </div>
        </div>
    </div>
</section><!--/#title-->

<section id="blog" class="container">

  <div class="search-form">
    <%= form_tag forum_theme_path(@forum_theme), method: :get do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscar Tópico", class: "form-control search-form-field"%>
      <%= submit_tag "Buscar", class: "search-form-button btn btn-default" %>
    <% end %>
  </div>
  <br>

  <div class="blog">
      <% unless @pages.count <= 1 %>
        <ul class="pagination pagination-lg">
          <% @pages.each do |page_number| %>
            <% if page_number.to_i != @page.to_i %>
              <li>
            <% else %>
              <li class="active">
            <% end %>
              <%= link_to "#{page_number}", "/forum_themes/#{ @forum_theme.id }?page=#{page_number}" %>
            </li>
          <% end %>
        </ul><!--/.pagination-->
      <% end %>
      <% @forum_topics.each do |topic| %>
          <div class="blog-item">
              <div class="blog-content">
                  <h3><%= link_to topic.title, forum_theme_forum_topic_path(@forum_theme, topic) %></h3>
                  <div class="entry-meta">
                      <span>
                        <i class="icon-user"></i>
                        <% unless topic.author.nil? %>
                          <%= topic.author %>
                        <% else %>
                          <%= "Anônimo" %>
                        <% end %>
                      </span>
                      <span>
                        <i class="icon-folder-close"></i>
                        <%= link_to forum_theme_path(@forum_theme), method: :get do %>
                          <%= @forum_theme.title %>
                        <% end %>
                      </span>
                      <span>
                        <i class="icon-calendar"></i>
                        <%= topic.created_at.strftime("%d/%m/%Y") %>
                      </span>
                      <span>
                        <i class="icon-comment"></i>i
                        <%= link_to forum_theme_forum_topic_path(@forum_theme, topic) do %>
                          <%= pluralize(topic.forum_posts.count, "Comment") %>
                        <% end %>
                      </span>
                  </div>
                  <% if topic.body.size > 140 %>
                    <%= topic.body[0..140] + "..." %>
                    <br><br>
                    <%= link_to forum_theme_forum_topic_path(@forum_theme, topic), class: "btn btn-default" do %>
                      Leia mais
                      <i class="icon-angle-right"></i>
                    <% end %>
                  <% else %>
                    <%= topic.body %>
                    <br><br>
                  <% end %>
                
                  <%= link_to 'apagar', forum_theme_forum_topic_path(@forum_theme, topic),
                      :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger' %>
                  <%= link_to 'editar', edit_forum_theme_forum_topic_path(@forum_theme, topic), class: 'btn btn-default' %>
              </div>
          </div><!--/.blog-item-->
      <%end%>
      <% unless @pages.count <= 1 %>
        <ul class="pagination pagination-lg">
          <% @pages.each do |page_number| %>
            <% if page_number.to_i != @page.to_i %>
              <li>
            <% else %>
              <li class="active">
            <% end %>
              <%= link_to "#{page_number}", "/forum_themes/#{ @forum_theme.id }?page=#{page_number}" %>
            </li>
          <% end %>
        </ul><!--/.pagination-->
      <% end %>
      <%= button_to 'Novo Tópico', new_forum_theme_forum_topic_path(@forum_theme), :class => "btn btn-default", :method => :get%>
  </div><!--/.blog-->
</section><!--/#blog-->