config/routes.rb
Rails.application.routes.draw do
  devise_for :ongs
  devise_for :admins

  resources :ongs
  get "forum_topics/:id/new_report_topic" => 'forum_topics#new_report_topic', as: :new_report_topic
  patch "forum_topics/:id/create_report_topic" => 'forum_topics#create_report_topic', as: :create_report_topic
  get "forum_topics/:id/new_report_post" => 'forum_topics#new_report_post', as: :new_report_post
  patch "forum_topics/:id/create_report_post" => 'forum_topics#create_report_post', as: :create_report_post
  get "admins/reports_index" => 'admins#reports_index'
  resources :forum_themes do
    resources :forum_topics
  end

  resources :forum_topics do
      resources :forum_posts
  end
  resources :forum_posts

  get "portal/list" => "portal_posts#list"
  get "portal/new" => "portal_posts#new"
  post "portal/new" => "portal_posts#create"

  resources :forum_themes
  resources :forum_topics
  resources :forum_posts
  

  resources :parsers do
    collection { post :importCare }
    collection { post :importRate }
  end

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'about'=> 'static_pages#about'
  get 'opendata' => 'static_pages#opendata'
  resources :mortality_rates
  resources :units
  resources :care_units
  resources :events
  resources :portal_posts
end

app/models/mortality_rate.rb
class MortalityRate < ActiveRecord::Base
	# Use forum_post as a rolify resource
  resourcify

	validates :regiao, presence: true
	validates :nome, presence: true
	validates :taxa, presence: true
end

app/controllers/mortality_rates_controller.rb
class MortalityRatesController < ApplicationController
  # Use this controller as a resource of CanCan and Rolify
  load_and_authorize_resource

  before_action :set_mortality_rate, only: [:show, :ediit, :update, :destroy]

  # The frequencies list must have this size
  # Be careful changing this line, some modifications must be done in the
  # controllers, HTMLs and JavaScripts of the application's charts.
  FREQUENCIES_LIST_SIZE = 6
  # This method creates a list with the mortality rate's frequencies 
  # for each region. The list contains indicators (in percentage) to
  # show mortality rate's seriousness. 
  # Each list contains 6 positions, in each position there are a percentage 
  # value that refers to how many cities are included in a arbitrary 
  # mortality rate range. 
  # For example, the first position indicates the frequency of cities with less 
  # than 5% in mortality rate's avaliations to a particular region.
  def index
    regions = ['Norte', 'Nordeste', 'Centro-Oeste', 'Sul', 'Sudeste']
    @mortality_rates_frequencies = Hash.new

    regions.each do |region_name|
      begin
        # Get a list of frequencies for each region
        @mortality_rates_frequencies[region_name.to_sym] = get_region_mortality_rate_frequency(region_name)
      rescue Errors::RegionNameError
        logger.info "[INFO] Skip the region #{region_name} and continue."
      end
    end
  end

  # Returns a new MortalityRate Model Object to be manually configured in the view form.
  def new
    # [TODO] This method should not exists unless it is used in the MortalityRate Parser.
    @mortality_rate = MortalityRate.new
  end

  # Tries to create and save a new MortalityRate object in the database and
  # redirects to the corresponding view.
  def create
    # [TODO] This method should not exists unless it is used in the MortalityRate Parser.

    @mortality_rate = MortalityRate.new(mortality_rate_params)

    respond_to do |format|
      if @mortality_rate.save
        format.html { redirect_to @mortality_rate, notice: 'Taxa de mortalidade foi criada com sucesso' }
        format.json { render :show, status: :created, location: @mortality_rate }
      else
        format.html { render :new }
        format.json { render json: @mortality_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # [TODO] This method should not exists unless it is used in the MortalityRate Parser.
    respond_to do |format|
      if @mortality_rate.update(mortality_rate_params)
        format.html { redirect_to @mortality_rate, notice: 'Taxa de mortalidade foi alterada com sucesso' }
        format.json { render :show, status: :ok, location: @mortality_rate }
      else
        format.html { render :edit }
        format.json { render json: @mortality_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # [TODO] This method should not exists unless it is used in the MortalityRate Parser.
    @mortality_rate.destroy
    respond_to do |format|
      format.html { redirect_to mortality_rates_url, notice: 'Taxa de mortalidade foi excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    # Takes an argument with the region name and returns a list with the
    # mortality rate's frequencies..
    # The list contains 6 positions, in each position there are a percentage 
    # value that refers to how many cities are included in a arbitrary 
    # mortality rate range. 
    def get_region_mortality_rate_frequency (region = nil)
      logger.debug "[DEBUG] Argument region: #{region}"
      logger.info "[INFO] Trying to get the mortality rate's frequencies list. Region: #{region}"

      # First, we need to verify if the region is registered as valid
      if is_region_valid? region
        logger.debug "[DEBUG] Region name validation method returned true."
        logger.info "[INFO] Region name is valid, continue."

        # Is necessary to get the number of registered region's data to calculate the average
        number_of_data_for_region = MortalityRate.where(regiao: region).count
        
        if number_of_data_for_region != 0
          # All the values below were arbitrarily selected, however it was designed to
          # give users a best experience reading the data.
          # Each nested list is a range with two limits, in percentage.
          # The first is the limit down, the second, limit up.
          # [PAY ATTENTION] be careful when you decide to change this list,
          # some modifications must be done in the index HTML and JavaScript view,
          # and this list should never be bigger than FREQUENCIES_LIST_SIZE!!
          rate_ranges = [[ 0.0 ,   8.0],
                        [ 8.0 ,  10.0],
                        [10.0 ,  12.0],
                        [12.0 ,  15.0],
                        [15.0 ,  20.0],
                        [20.0 , 100.0]]

          # Respect the list size limit
          # DO NOT remove this line!
          rate_ranges = rate_ranges[0...FREQUENCIES_LIST_SIZE]

          region_rates_frequency = [] # It will store the 6 frequency values.

          # Iterate over rate ranges and, for each range, calculate the frequency of cities
          # that belongs to the region and has the mortality rate included in the range.
          rate_ranges.each do |each_range|
            begin
              rates_per_range_counter = count_number_of_rates_in_limits(region, each_range[0], each_range[1])
              rates_per_range_frequency = (rates_per_range_counter.to_f/number_of_data_for_region.to_f)*100.0

              logger.debug "[DEBUG] each_range: #{each_range
              }, rates_per_range_counter: #{rates_per_range_counter
              }, number_of_data_for_region: #{number_of_data_for_region
              }, rates_per_range_frequency: #{rates_per_range_frequency}"

              region_rates_frequency << rates_per_range_frequency # Append the calculated frequency.
            rescue Errors::InvalidPercentageValueError
              logger.error "[ERROR] Any limit out of range: #{each_range}"
              logger.info "[INFO] Skip this range, going to the next range in the rate ranges list."
            end
          end

          logger.debug "[DEBUG] Exited rate_ranges loop with region_rates_frequency: #{region_rates_frequency}"
          return region_rates_frequency
        else
          # There is no data available to be calculated for this region
          logger.info "[INFO] There is no data for this region name."
          logger.debug "[DEBUG] number_of_data_for_region: 0"
          logger.warn "[WARN] There is no data for the region named \"#{region}\""

          return [0] * FREQUENCIES_LIST_SIZE# Displays nothing in the chart
        end
      else
        # The region name is invalid
        logger.debug "[DEBUG] Region name validation method returned false."
        logger.info "[INFO] Region name is invalid, break."
        logger.error "[ERROR] This region name is not registered: #{region}."

        # Must raise an invalid region name exception
        raise Errors::RegionNameError 
      end
    end

    # Takes three arguments, the first is the region name, necessary to
    # load all region rows of the database. The second and third arguments
    # are the limits. It returns how many region's cities have the mortality rate
    # between limits.
    # This method takes on region as valid data, please, be sure you've verified this before
    def count_number_of_rates_in_limits(region, limit_down, limit_up)
      logger.info "[INFO] Trying to count region's rates in the limits (#{limit_down} , #{limit_up})"

      if (is_limit_valid? limit_down) && (is_limit_valid? limit_up) # Verify if limits are valid
        rates_in_limits_counter = 0 # Counter of cities that rates are included in the limits.

        region_mortality_rate = MortalityRate.where(regiao: region) # Get all database's rows with the region name

        # Iterate over the loaded rows objects and increase the counter when find any that fits
        region_mortality_rate.each do |each_rate| 

          # This step is necessary because in the database's "taxa" column, the
          # data is storad as a string and instead of being separated by a dot, it
          # is separated by a comma, preventing direct convertion to float.
          fixed_rate_value = each_rate.taxa.gsub(',','.').to_f

          logger.debug "[DEBUG] region: #{region
          }, each_rate.nome: #{each_rate.nome
          }, each_rate.taxa: #{each_rate.taxa
          }, fixed_rate_value: #{fixed_rate_value}."

          if fixed_rate_value >= limit_down && fixed_rate_value < limit_up
            rates_in_limits_counter += 1
          else
            # Do nothing and continue
          end
        end
        
        logger.info "[INFO] Found #{rates_in_limits_counter} rates to the region: \"#{region}\""
        logger.debug "[DEBUG] Rates in the limits (#{limit_down}, #{limit_up}) | Got: #{rates_in_limits_counter}."
        return rates_in_limits_counter
      else
        # Limits are invalid
        logger.warn "[WARN] Limits are invalid!"
        logger.debug "[DEBUG] Invalid limit_down: #{limit_down} or limit_up: #{limit_up}"

        # Must raise an error for the invalid limit.
        raise Errors::InvalidPercentageValueError
      end
    end

    # Verify if limit is a valid value
    # It is a percentage value, so it
    # must be 0 <= x <= 100 and a float value.
    def is_limit_valid?(limit)
      return (limit.class == Float &&
              limit >= 0.0         &&
              limit <= 100.0)
    end

    # All the available region's name.
    # To add another region, take care with the index method and the view,
    def is_region_valid?(region)
      permitted_regions = ['Norte', 'Nordeste', 'Sul', 'Sudeste', 'Centro-Oeste']
      return permitted_regions.include? region
    end

    def set_mortality_rate

app/helpers/mortality_rates_helper.rb
module MortalityRatesHelper
end

app/views/mortality_rates/_form.html.erb
<section id="title" class="emerald">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1><%= action_name %></h1>
        <p><%= action_command %></p>
      </div>
    </div>
  </div>
</section>

<section id="portfolio" class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@mortality_rate) do |f| %>
      <% if @mortality_rate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@mortality_rate.errors.count, "Erro") %> prohibited this mortality_rate from being saved:</h2>

          <ul>
          <% @mortality_rate.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :regiao %>
        <%= f.text_field :regiao, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :taxa %>
        <%= f.text_field :taxa, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit action_name, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</section>

app/views/mortality_rates/_mortality_rate_chart.html.erb
<!-- Configuration of the mortality rate chart -->
<script>
$(document).ready(function() {
  $(function () {
    // Parse the data from an inline table using the Highcharts Data plugin
    $('#container').highcharts({
        data: {
            table: 'freq',
            startRow: 1, // Init of the char row counter.
            endRow: 6,	 // Control of the number of slices of the chart.
            endColumn: 6 // Control of the number of subtitles.
        },
        chart: {
            polar: true,
            type: 'column'
        },
        title: {
            text: 'Taxa de mortlidade entre mulheres vítimas de violência.'
        },
        subtitle: {
            text: 'Fonte: dadosabertos.gov.br'
        },
        pane: {
            size: '85%'
        },
        legend: {
            align: 'right',
            verticalAlign: 'top',
            y: 100,
            layout: 'vertical'
        },
        xAxis: {
            tickmarkPlacement: 'on'
        },
        yAxis: {
            min: 0,
            endOnTick: false,
            showLastLabel: true,
            title: {
                text: 'Taxa de Mortalidade (%)'
            },
            labels: {
                formatter: function () {
                    return this.value + '%';
                }
            },
            reversedStacks: false
        },
        tooltip: {
            valueSuffix: '%'
        },
        plotOptions: {
            series: {
                stacking: 'normal',
                shadow: false,
                groupPadding: 0,
                pointPlacement: 'on'
            }
        }
    });
  });
});
</script>

app/views/mortality_rates/_mortality_rate_charts_external_scripts.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/highcharts-more.js"></script>
<script src="http://code.highcharts.com/modules/data.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

app/views/mortality_rates/edit.html.erb
<%= render 'form', {action_name: "Editar taxa de mortalidade", action_command: "Corrija possíveis erros nos dados desta taxa de mortalidade."} %>

app/views/mortality_rates/index.html.erb
<section id="title" class="emerald">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <!-- Top title of the page -->
				<h1>Lista de mortalidade das 5 regiões do Brasil</h1>
        <p></p>
      </div>
    </div>
  </div>
</section>

<section id="portfolio" class="container">

	<!-- Render basic configuration of the mortality rate chart -->
	<!-- This sintax is necessary to render javascript when the request comes from a link -->
	<%= render(:partial =>'mortality_rate_chart', :format => :js) %>

	<!-- Place where is displayed the mortality rate chart -->
	<div id="container" style="min-width: 420px; max-width: 600px; height: 400px; margin: 0 auto"></div>

	<!-- Here, we put all available data in repective 'tr' container to display in the chart view -->
	<div style="display:none">

		<table id="freq" border="0" cellspacing="0" cellpadding="0">

			<!-- This 'tr' won't be displayed -->
			<tr nowrap bgcolor="#CCCCFF">
				<th colspan="9" class="hdr">Gráfico de Mortalidade</th> 
			</tr>

			<!-- This is the subtitles of the chart -->
			<tr nowrap bgcolor="#CCCCFF">
				<!-- Here, the first 'th' will never be displayed -->
	      <th class="freq">Taxas</th>
				<th class="freq">&lt; 8 %</th>
				<th class="freq">8-10 %</th>
				<th class="freq">10-12 %</th>
				<th class="freq">12-15 %</th>
				<th class="freq">15-20 %</th>
				<th class="freq">&gt; 20 %</th>
			</tr>

			<!-- Begginig in this section, all the rate data of each region
			should be displayed in the respective block. -->

	        <%= @mortality_rates_frequencies.each do |region_name, frequencies_of_rates| %>
	          <tr nowrap>
	            <td class="dir"><%= region_name.to_s %></td>
	            <%= frequencies_of_rates.each do |each_mortality_rate_frequency| %>
				  <th class="data"><%= each_mortality_rate_frequency %></th>
	            <% end %>
	          </tr>
	        <% end %>
		</table>
	</div>
	<br>

	<% if ong_signed_in? and current_ong.has_role? :admin %>
		<%= link_to 'Nova taxa de mortalidade', new_mortality_rate_path, class: 'btn btn-default' %>
	<% end %>
</section>

app/views/mortality_rates/new.html.erb
<%= render 'form', {action_name: "Criar taxa de mortalidade", action_command: "Adicione uma taxa de mortalidade ao nosso banco de dados."} %>

app/views/mortality_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Regiao:</strong>
  <%= @mortality_rate.regiao %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @mortality_rate.nome %>
</p>

<p>
  <strong>Taxa:</strong>
  <%= @mortality_rate.taxa %>
</p>

<% if ong_signed_in? and current_ong.has_role? :admin %>
 	<%= link_to 'Edit', edit_mortality_rate_path(@mortality_rate) %> |
	<%= link_to 'Back', mortality_rates_path %>
<% end %>