config/routes.rb
Rails.application.routes.draw do
  devise_for :ongs
  devise_for :admins

  resources :ongs
  get "forum_topics/:id/new_report_topic" => 'forum_topics#new_report_topic', as: :new_report_topic
  patch "forum_topics/:id/create_report_topic" => 'forum_topics#create_report_topic', as: :create_report_topic
  get "forum_topics/:id/new_report_post" => 'forum_topics#new_report_post', as: :new_report_post
  patch "forum_topics/:id/create_report_post" => 'forum_topics#create_report_post', as: :create_report_post
  get "admins/reports_index" => 'admins#reports_index'
  resources :forum_themes do
    resources :forum_topics
  end

  resources :forum_topics do
      resources :forum_posts
  end
  resources :forum_posts

  get "portal/list" => "portal_posts#list"
  get "portal/new" => "portal_posts#new"
  post "portal/new" => "portal_posts#create"

  resources :forum_themes
  resources :forum_topics
  resources :forum_posts
  

  resources :parsers do
    collection { post :importCare }
    collection { post :importRate }
  end

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'about'=> 'static_pages#about'
  get 'opendata' => 'static_pages#opendata'
  resources :mortality_rates
  resources :units
  resources :care_units
  resources :events
  resources :portal_posts
end

app/models/portal_post.rb
class PortalPost < ActiveRecord::Base
  # Use portal_post as a rolify resource
  resourcify

  # Each portal_post has an owner
  belongs_to :ong
  
  validates :author, presence: true
  # Paperclip gem sintax for upload image files.
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/
  validates :author, presence: true
  validates :title, presence: true
  validates :body, presence: true

  # Method to search for some posts by a string
  def self.search(search)
    # Search by title, author and body
    where("title LIKE ? OR author LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/api/v1/portal_posts_controller.rb
module Api
  module V1
    class PortalPostsController < ApplicationController
      respond_to :json

      def index
        respond_with PortalPost.all
      end

      def show
        respond_with PortalPost.find(params[:id])
      end
    end
  end
end

app/controllers/portal_posts_controller.rb
class PortalPostsController < ApplicationController
  before_action :set_portal_post, only: [:show, :edit, :update, :destroy]

  # Use this controller as a resource of CanCan and Rolify
  load_and_authorize_resource

  # GET /portal_posts
  def index
    @portal_posts = PortalPost.all
    if params[:search]
      @portal_posts = PortalPost.search(params[:search]).order("created_at DESC")
    else
      @portal_posts = PortalPost.all.order('created_at DESC')
    end
  end

  # GET /portal_posts/<post:id>
  def show
  end

  # GET /portal_posts/new
  def new
    @portal_post = PortalPost.new
  end

  # GET /portal_posts/<post:id>/edit
  def edit
  end

  # POST /portal_posts
  def create
    @portal_post = PortalPost.new(portal_post_params)

    # Associate the portal_post created along with its owner
    @portal_post.ong_id = current_ong.id 

    if @portal_post.save
      flash[:success] = "A postagem \"#{ @portal_post.title }\" foi criada com sucesso."
      redirect_to portal_posts_url
    else
      render :new
    end
  end

  # PATCH/PUT /portal_posts/<post:id>
  def update
    if @portal_post.update(portal_post_params)
      flash[:success] = "A postagem \"#{ @portal_post.title }\" foi atualizada com sucesso."

      redirect_to @portal_post
    else
      render :edit
    end
  end

  # DELETE /portal_posts/<post:id>
  def destroy
    @portal_post.destroy
    redirect_to portal_posts_url
  end

  private
    def set_portal_post
      @portal_post = PortalPost.find(params[:id])
    end

    def portal_post_params
      params.require(:portal_post).permit(:author, :title, :body, :image_file)
    end
end

app/views/portal_posts/_form_new_edit.html.erb
<%= tinymce_assets %>

<section id="title" class="emerald">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1><%= action_command %></h1>
				<p>As notícias são fundamentais para manter os usuários sempre informados de seus direitos, o que fazer em momentos críticos e atualizados a cerca do tema.</p>
			</div>
		</div>
	</div>
</section>

<section id="portfolio" class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for(@portal_post) do |f| %>
				<div class="field">
					<p><b>Autor</b></p>
					<%= f.text_field :author, class: 'form-control' %>
				</div>
				<div class="field">
					<p><b>Título</b></p>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
				<div class="field">
					<p><b>Texto</b></p>
					<%= f.text_area :body, content: "", rows: 15, class: 'form-control tinymce' %>
					<%= tinymce %>
				</div>
				<div class="field">
					<p><b>Imagem</b></p>
					<%= f.file_field :image_file %>
				</div>
				</br><%= f.submit action_command, class: "btn btn-primary" %></br></br>
			<% end %>
		</div>
	</div>
</section>

app/views/portal_posts/_last_posts.html.erb
<section id="recent-works">
    <div class="container">
        <div class="row">
            <!-- Service explanation -->
            <div class="col-md-3">
                <h3>Últimas notícias</h3>
                <p>Acompanhe as últimas notícias de nosso portal, políticas públicas, legislação, direito e muito mais informações.</p>
                <%= link_to "Mais Notícias", portal_posts_path, class: "btn btn-default" %>
                <p class="gap"></p>
            </div>

            <div class="col-md-9">
                <div id="scroller" class="carousel slide">
                    <div class="carousel-inner">

                      <% @ungrouped_last_posts.each do |each_post| %>
                        <% if @ungrouped_last_posts.first == each_post %>
                          <div class="item active">
                        <% else %>
                          <div class "item">
                        <% end %>
                                  <div class="col-xs-4">
                                      <div class="portfolio-item">
                                          <div class="item-inner">
                                              <%= image_tag(each_post.image_file.url(), class: "img-responsive") %>
                                              <h5>
                                                 <%= each_post.title %>
                                              </h5>
                                              <div class="overlay">
                                                  <%= link_to each_post, class: "preview btn btn-danger", title: "Veja mais" do %>
                                                    <!-- Eye icon" -->
                                                    <i class="icon-eye-open"></i>
                                                  <% end %>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                        </div><!-- End of each item -->
                      <% end %>


                    </div><!-- End of carrousel-inner -->
                </div><!-- End of scroller -->
            </div><!-- End of col-md-9 -->
        </div><!--/.row-->
    </div>
</section><!--/#recent-works-->

app/views/portal_posts/edit.html.erb
<% provide(:title, "| Portal") %>
<%= render 'form_new_edit', {action_name: "Editar Postagem", action_command: "Salvar modificações"} %>

app/views/portal_posts/index.html.erb
<% provide(:title, "| Portal") %>

<section id="title" class="emerald">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1>Portal de Notícias e Informações</h1>
				<p>Acompanhe as notícias de nosso portal, políticas públicas, legislação, direito e muito mais informações.</p>
			</div>
		</div>
	</div>
</section>

<section id="portfolio" class="container">
    <div class="search-form">
      <%= form_tag(portal_posts_path, method: "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar Notícia", class: "form-control search-form-field"%>
        <%= submit_tag "Buscar", class: "search-form-button btn btn-default" %>
      <% end %>
    </div>
    <br>
	<div class="portal-posts">
      <% if @portal_posts.present? %>
		<% @portal_posts.each do |post| %>
			<%= link_to(post) do %>
				<div class="portal-post ">
					<%if post.image_file.present? %>
						<%= image_tag(post.image_file.url(), class: "image center-block") %>
					<%else%>
						<%= image_tag("nikn_default_banner.png", class: "image center-block") %>
					<%end%>
					<p class="title"><%= post.title %></p>
				</div>
			<% end %>
		<% end %>
      <% else %>
        <div class="post-not-found">
          <br />
          <p>Desculpe, nenhuma notícia foi encontrada.</p>
          <br />
        </div>
      <% end %>
	</div>

<% if ong_signed_in? %>
	<a href="/portal_posts/new">
		<button type="button" class="btn btn-default center-block" aria-label="Left Align">
			<p>Nova Postagem</p>
		</button>
	</a>
<% end %>

</section>

app/views/portal_posts/new.html.erb
<% provide(:title, "| Portal") %>
<%= render 'form_new_edit' , {action_name: "Nova Postagem", action_command: "Criar nova postagem"} %>

app/views/portal_posts/show.html.erb
<% provide(:title, "| Portal") %>

<section id="title" class="emerald">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1><%= @portal_post.title %></h1>
				<p><%= @portal_post.created_at.strftime("%d/%M/%Y") %>, por <em><%= @portal_post.author %></em></p>
			</div>
		</div>
	</div>
</section>

<section id="portfolio" class="container text-center">
	<div class="show-post text-left">
		<div style="display:block" class="text-center">
		<%if @portal_post.image_file.present? %>
			<%= image_tag(@portal_post.image_file.url(), class: "image center-block") %>
		<%else%>
			<%= image_tag("nikn_default_banner.png", class: "image center-block") %>
		<%end%>
		</div>
		<br><br><%= @portal_post.body.html_safe %><br><br>

		<div class="portal-buttons", style="display:inline">
			<% if ong_signed_in? and (current_ong.has_role? :admin or (current_ong.has_role? :ong and @portal_post.ong_id === current_ong.id)) %>
				<%= link_to(edit_portal_post_path(@portal_post), type: "button", class: "btn btn-default",:method => :get) do %>
					Editar<!-- <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> -->
				<% end %>
				<%= link_to(@portal_post, method: :delete, data: { confirm: 'Deseja realmente excluir esta notícia?' }, type: "button", class: "btn btn-danger") do %>
					Excluir<!-- <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> -->
				<% end %>
			<% end %>
		</div>

		<div class="social-buttons", style="display:inline">
			<div class="twitter_button each_button"><%= tweet_button %></div>
			<div class="facebook_button each_button"><%= like_button(1627715594161634) %></div>
			<div class="pinit_button each_button"><%= pinit_button %></div>
		</div>
	</div>
</section>