config/routes.rb
Rails.application.routes.draw do
  devise_for :ongs
  devise_for :admins

  resources :ongs
  get "forum_topics/:id/new_report_topic" => 'forum_topics#new_report_topic', as: :new_report_topic
  patch "forum_topics/:id/create_report_topic" => 'forum_topics#create_report_topic', as: :create_report_topic
  get "forum_topics/:id/new_report_post" => 'forum_topics#new_report_post', as: :new_report_post
  patch "forum_topics/:id/create_report_post" => 'forum_topics#create_report_post', as: :create_report_post
  get "admins/reports_index" => 'admins#reports_index'
  resources :forum_themes do
    resources :forum_topics
  end

  resources :forum_topics do
      resources :forum_posts
  end
  resources :forum_posts

  get "portal/list" => "portal_posts#list"
  get "portal/new" => "portal_posts#new"
  post "portal/new" => "portal_posts#create"

  resources :forum_themes
  resources :forum_topics
  resources :forum_posts
  

  resources :parsers do
    collection { post :importCare }
    collection { post :importRate }
  end

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'about'=> 'static_pages#about'
  get 'opendata' => 'static_pages#opendata'
  resources :mortality_rates
  resources :units
  resources :care_units
  resources :events
  resources :portal_posts
end

app/models/care_unit.rb
class CareUnit < ActiveRecord::Base
  # Impossible to create a care unit without a district
  validates(:district, presence: true)
  # The district field should have only 2 upercase characters
  district_regex = /\A[A-Z]{2}\z/
  wrong_format_message = "Only allow 2 upercase characters."
  validates(:district, format: { with: district_regex, message: wrong_format_message })
  # The size of the string must be 2 (DF, MG, BA)
  VALID_DISTRICT_STRING_SIZE = 2
  validates(:district, length: { is: VALID_DISTRICT_STRING_SIZE })

  # Impossible to create a care unit without a category
  validates(:category, presence: true)
  CATEGORY_MAX_LENGTH = 150
  CATEGORY_MIN_LENGTH = 10
  validates(:category, length: { in: CATEGORY_MIN_LENGTH...CATEGORY_MAX_LENGTH })

  # Impossible to create a care unit without an institution
  validates(:institution, presence: true)
  INSTITUTION_MAX_LENGTH = 150
  INSTITUTION_MIN_LENGTH = 10
  validates(:institution, length: { in: INSTITUTION_MIN_LENGTH...INSTITUTION_MAX_LENGTH })

  # Impossible to create a care unit without a description of its services
  validates(:description, presence: true)
  DESCRIPTION_MAX_LENGTH = 2000
  DESCRIPTION_MIN_LENGTH = 100
  validates(:description, length: { in: DESCRIPTION_MIN_LENGTH...DESCRIPTION_MAX_LENGTH })

  # Impossible to create a care unit without a name
  validates(:name, presence: true)
  NAME_MAX_LENGTH = 100
  NAME_MIN_LENGTH = 10
  validates(:name, length: { in: NAME_MIN_LENGTH...NAME_MAX_LENGTH })

  # Impossible to create a care unit without an physic address
  validates(:address, presence: true)
  ADDRESS_MAX_LENGTH = 150
  ADDRESS_MIN_LENGTH = 30
  validates(:address, length: { in: ADDRESS_MIN_LENGTH...ADDRESS_MAX_LENGTH })

  # Impossible to create a care unit without a valid zipcode
  validates(:zip_code, presence:true)
  # The zipcode should be like xxxxx-xxx
  zip_code_regex = /\A[0-9]{5}-[0-9]{3}\z/
  wrong_zip_code_format_message = "The zip code should be in the 55555-333 format."
  validates(:zip_code, format: { with: zip_code_regex, message: wrong_zip_code_format_message })

  # There is possible to create care unit without a email, but
  # if the email is present, it should be in the following format
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, format: { with: email_regex }, unless: :blank_email?)

  # Impossible to create a care unit without a city
  validates(:city, presence: true)
  CITY_MAX_LENGTH = 50
  CITY_MIN_LENGTH = 2
  validates(:city, length: { in: CITY_MIN_LENGTH...CITY_MAX_LENGTH })

  # Impossible to create a care unit without a phone number
  validates(:phone, presence: true)
  # The format of the number should be (22)4444-4444 or (22) 55555-4444
  phone_number_regex = /\A\([0-9]{2}\)\s*[0-9]{4,6}-[0-9]{4,6}\z/
  wrong_phone_number_format_message = "The phone number format should be (22)4444-4444 or (22) 55555-4444."
  validates(:phone, format: { with: phone_number_regex, message: wrong_phone_number_format_message })

  # There is possible to create a care unit without a site.
  # Some institutions don't have a web page.

  # Impossible to create a care unit without a latitude and longitude coordinates

  validates(:latitude, presence: true)
  validates(:longitude, presence: true)

  # This is necessary to the Google Map plugin works.
  geocoded_by :address
  geocoded_by :district
  geocoded_by :city
  after_validation :geocode

  # Method to turn the model searchable
  # This will work in development with SQLite. If you switch to
  # PostgreSQL in productionm you may need to change
  def self.search(search)
    where("category LIKE ? OR name LIKE ? OR city LIKE ? OR institution LIKE ? OR site LIKE ? OR address LIKE ?",
    "%#{search}%", "%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%")
  end

  private
    # Method to verify if the email field wasn't filled
    def blank_email?
      return email == ""
    end
end

app/controllers/api/v1/care_units_controller.rb
module Api
  module V1
    class CareUnitsController < ApplicationController
      respond_to :json

      def index
        respond_with CareUnit.all
      end

      def show
        respond_with CareUnit.find(params[:id])
      end

    end
  end
end

app/controllers/care_units_controller.rb
class CareUnitsController < ApplicationController
  before_action :set_care_unit, only: [:show, :edit, :update, :destroy]

  # Use this controller as a resource of CanCan and Rolify
  skip_authorization_check
  def index
    # This conditional structure returns to the view the result of
    # the user search in case of a request.
    if params[:search]
      @care_units = CareUnit.search(params[:search])
    else
      @care_units = CareUnit.all
    end

    # This hash returns all the map points to plot in the Google map plugin.
    @hash = Gmaps4rails.build_markers(@care_units) do |care_unit, marker|
      marker.lat care_unit.latitude
      marker.lng care_unit.longitude
      marker.infowindow care_unit.name
    end
  end

  def show
  end

  def new
    @care_unit = CareUnit.new
  end

  def edit
  end

  def create
    @care_unit = CareUnit.new(care_unit_params)

    respond_to do |format|
      if @care_unit.save
        format.html { redirect_to care_units_path, notice: 'Care unit was successfully created.' }
        format.json { render :index, status: :created, location: care_units_path }
      else
        format.html { render :new }
        format.json { render json: @care_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @care_unit.update(care_unit_params)
        format.html { redirect_to care_units_path, notice: 'Care unit was successfully updated.' }
        format.json { render :index, status: :ok, location: care_units_path }
      else
        format.html { render :edit }
        format.json { render json: @care_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @care_unit.destroy
    respond_to do |format|
      format.html { redirect_to care_units_path, notice: 'Care unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_care_unit
      @care_unit = CareUnit.find(params[:id])
    end

    def care_unit_params
      params.require(:care_unit).permit(:district, :category, :institution, :description, :name, :address, :zip_code, :city, :phone, :email, :site, :latitude, :longitude)
    end
end

app/helpers/care_units_helper.rb
module CareUnitsHelper
end

app/views/care_units/_form.html.erb
<section id="title" class="emerald">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1><%= action_name %></h1>
        <p><%= action_command %></p>
      </div>
    </div>
  </div>
</section>

<section id="portfolio" class="container">
  <%= form_for(@care_unit) do |f| %>
    <div class="col-md-6 col-md-offset-3">
      <% if @care_unit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@care_unit.errors.count, "Erro") %> prohibited this care_unit from being saved:</h2>
          <ul>
          <% @care_unit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <p><b>Distrito</b></p>
        <%= f.text_field :district, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Categoria</b></p>
        <%= f.text_field :category, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Instituição</b></p>
        <%= f.text_field :institution, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Descrição</b></p>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Nome</b></p>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Endereço</b></p>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>CEP</b></p>
        <%= f.text_field :zip_code, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Cidade</b></p>
        <%= f.text_field :city, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Telefone</b></p>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>E-mail</b></p>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Site</b></p>
        <%= f.text_field :site, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Latitude</b></p>
        <%= f.text_field :latitude, class: 'form-control' %>
      </div>
      <div class="field">
        <p><b>Longitude</b></p>
        <%= f.text_field :longitude, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit action_name, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</section>

app/views/care_units/_google_maps_external_scripts.html.erb
<!-- Google maps external scripts -->
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

app/views/care_units/edit.html.erb
<%= render 'form', {action_name: "Editar unidade de Atendimento", action_command: "Edite uma unidade de atendimento, atualize os dados ou adicione novas informações."} %>

app/views/care_units/index.html.erb
<section id="title" class="emerald">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1>Unidades de Atendimento à Mulher*</h1>
        <p></p>
      </div>
    </div>
  </div>
</section>

<div class='col-md-12 uda-map'>
  <div id="multi_markers" style='width: 100%; height: 600px;'></div>
</div>


<%= javascript_tag do %>
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
      var markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
<% end %>

<section id="portfolio" class="container">
  <div class="img-responsive aspect data_background"></div>
  <br>
  <div class="search-form">
    <%= form_tag(care_units_path, method: "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscar UDA", class: "form-control search-form-field"%>
      <%= submit_tag "Buscar", class: "search-form-button btn btn-default" %>
    <% end %>
  </div>
  <% if @care_units.present? %>
    <table class="table table-striped w">
      <thead class="text-position">
        <tr>
          <th>Nome</th>
          <th>Categoria</th>
          <th>Instituição</th>
          <th>Cidade</th>
        </tr>
      </thead>
      <tbody class="text-position">
        <% @care_units.each do |unit| %>
          <tr>
            <td><%= unit.name %></td>
            <td><%= unit.category %></td>
            <td><%= unit.institution %></td>
            <td><%= unit.district %></td>
            <td><a class="btn" href="#" id="openBtn<%= unit.id =%>">Ver detalhes »</a></td>
          </tr>

  <div id="myModal<%= unit.id %>" class="modal fade" tabindex='-1' role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h3><%= unit.name %></h3>
        </div>

        <div class="modal-body">

          <!-- Display the UDA information -->
          <div class="uda-information">
            <h2>Informações:</h2>
            <dl>
              <!-- Print the unit care address and district -->
              <dt>
                <strong>
                  Endereço:
                </strong>
              </dt>
              <dd>
              <%= unit.address + " - " + unit.city + " - " + unit.district %>
              </dd>

              <!-- Print the unit care's phone number -->
              <dt>
                <strong>
                  Telefone:
                </strong>
              </dt>
              <dd>
                <%= unit.phone %>
              </dd>

              <!-- Print the unit care's category -->
              <dt>
                <strong>
                  Categoria:
                </strong>
              </dt>
              <dd>
                <%= unit.category %>
              </dd>
            </dl>
            <br>
            <!-- Diplay this only if the user clicks in the link -->
            <div class="col-md-12 container">
              <div class="row">
                <div class="span4 collapse-group">
                  <p><a class="modalbtn" href="#">Mais informações »</a></p>
                  <div class="collapse">
                    <h2>Instituição:</h2>
                    <p><%= unit.institution %>
                    <hr>
                    <h2>Descrição dos serviços:</h2>
                    <div class="unit-description">
                      <%= unit.description %>
                    </div>
                    <hr/>
                    <!-- Display some informations like e-mail and site -->
                    <div class="aditional-information">
                      <dl>
                        <!-- Email -->
                        <dt>
                            Email:
                        </dt>
                        <dd>
                          <% if unit.email.present? %>
                            <%= unit.email %>
                          <% else %>
                            <p> - </p>
                          <% end %>
                        </dd>

                        <!-- Site -->
                        <dt>
                            Site:
                        </dt>
                        <dd>
                          <% if unit.site.present? %>
                            <%= unit.site %>
                          <% else %>
                            <p> - </p>
                          <% end %>
                        </dd>
                      </dl>
                    </div><!--End of aditional information -->
                  </div><!-- End of collapse -->
                </div><!-- End of collapse-group -->
              </div><!-- End of row -->
            </div><!-- End of container -->
          </div><!-- End of UDA information -->
  <!-- Javascript to collapse some text -->
  <%= javascript_tag do %>
    $('.row .modalbtn').on('click', function(e) {
      e.preventDefault();
      var $this = $(this);
      var $collapse = $this.closest('.collapse-group').find('.collapse');
      $collapse.collapse('toggle');
    });
  <% end %>
        </div>

        <div class="modal-footer">
          <%= link_to 'Edit', edit_care_unit_path(unit) %> |
          <button class="btn" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>

  <%= javascript_tag do %>
    $('#openBtn<%= unit.id %>').click(function(){
      $('#myModal<%= unit.id %>').modal({show:true})
    });
  <% end %>

        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="not-found">
      <p>Desculpe, nenhuma UDA encontrada.</p>
    </div>
  <% end %>
  <br>
  <div class="col-md-12 advisor">
    <p><strong>*</strong> Até o momento só estão disponíveis dados sobre Unidades de Atendimento na região do Distrito Federal.</p>
  </div>
  <!-- New Care Unit Button -->
  <%= link_to 'Cadastrar UDA', new_care_unit_path, class: "btn btn-default" %>
</section><!-- #Portfolio .container -->

app/views/care_units/new.html.erb
<%= render 'form', {action_name: "Criar unidade de atendimento", action_command: "Adicione uma unidade de atendimento ao nosso banco de dados."} %>